### ISSUE TITLE
Pin EDK version to prevent unexpected breakages

### ISSUE THREAD

**Issue by aaronsteers** [meltano/dbt-ext#20]
Currently `pyproject.toml` pins to main branch here:

https://github.com/meltano/dbt-ext/blob/d8fa373383a6104e40f838e7a5726bfdc0d769c0/pyproject.toml#L28

This likely is causing the recent breakage we've been seeing in Slack, where a 'fix' likely broke this implementation, which had a matching/symmetrical bug.

Slack conversation: https://meltano.slack.com/archives/C029CUM7ATD/p1674002101903899?thread_ts=1673965878.190399&cid=C029CUM7ATD

**Comment by WillDaSilva** [comment]
I've released/tagged EDK v0.1.0: https://github.com/meltano/edk/releases/tag/v0.1.0

**Comment by aaronsteers** [comment]
Since [this one](https://github.com/meltano/edk/pull/52) is closed, I've lowered urgency from "Highest" to "High". Still worth expediting but okay if it isn't a 24-hour turnaround time. Thanks, @WillDaSilva  for picking this up.
