### ISSUE TITLE
[Bug]: the provided staging + prod Redshift profiles are invalid if not using IAM auth

### ISSUE THREAD

**Issue by menzenski** [meltano/dbt-ext#26]
### Package Version

62fc87a7dba94ac8d618e22a0aa0daf702da4aff

### Python Version

NA

### Operating System

macOS

### Description

The provided Redshift `dev` profile supplies a default value for the `iam_duration_seconds` setting:

```yaml
 iam_duration_seconds: "{{ env_var('DBT_REDSHIFT_IAM_DURATION_SECONDS', 900) | int }}" # optional
```

The provided Redshift `staging` and `prod` profiles do not:

```yaml
iam_duration_seconds: "{{ env_var('DBT_REDSHIFT_IAM_DURATION_SECONDS', '') }}" # optional
```

We're not using IAM auth for Redshift, so we commented out the `method` setting in all profiles:

```yaml
iam_duration_seconds: "{{ env_var('DBT_REDSHIFT_IAM_DURATION_SECONDS', '') }}" # optional
```

However, this leaves the non-dev profiles in an invalid state, and `dbt debug` throws an error (see below).

The fix for this issue is to add the default value of 900 seconds rather than the empty string. Is there a reason this shouldn't be the default for all provided profiles?

### Code

```python
Extension executing `dbt debug`...
14:46:14  Running with dbt=1.4.4
dbt version: 1.4.4
python version: 3.11.1
python path: /Users/matt/dev/paw_elt/src/.meltano/utilities/dbt-redshift/venv/bin/python
os info: macOS-12.6-x86_64-i386-64bit
Using profiles.yml file at /Users/matt/dev/paw_elt/src/transform/profiles/redshift/profiles.yml
Using dbt_project.yml file at /Users/matt/dev/paw_elt/src/transform/dbt_project.yml

Configuration:
  profiles.yml file [ERROR invalid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

1 check failed:
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "meltano", target "staging" invalid: '' is not of type 'integer'




error invoking dbt None        error_message=dbt invocation failed returncode=1
```

**Comment by tayloramurphy** [comment]
@menzenski I don't see any reason they shouldn't be. 

@pnadolny13 would you be willing to get some PRs up to make the change?

**Comment by pnadolny13** [comment]
@tayloramurphy yep I can do that!

@aaronsteers since I think you might have assisted Florian when he built this, do you know if there was any reason for intentionally not setting a default here?

**Comment by aaronsteers** [comment]
@pnadolny13 - re:

> do you know if there was any reason for intentionally not setting a default here?

No reason I'm aware of. The proposed change looks good 👍
